In [1]:
import pandas as pd
import numpy as np
from numpy import nan

In [2]:
apps = pd.read_csv('F:\HiCounselor\datasets\playstore_apps.csv', index_col='App')
apps.head()

Category  Rating  \
App                                                                          
Photo Editor & Candy Camera & Grid & ScrapBook      ART_AND_DESIGN     4.1   
Coloring book moana                                 ART_AND_DESIGN     3.9   
U Launcher Lite – FREE Live Cool Themes, Hide Apps  ART_AND_DESIGN     4.7   
Sketch - Draw & Paint                               ART_AND_DESIGN     4.5   
Pixel Draw - Number Art Coloring Book               ART_AND_DESIGN     4.3   

                                                     Reviews  Size  \
App                                                                  
Photo Editor & Candy Camera & Grid & ScrapBook         159.0   19M   
Coloring book moana                                    967.0   14M   
U Launcher Lite – FREE Live Cool Themes, Hide Apps   87510.0  8.7M   
Sketch - Draw & Paint                               215644.0   25M   
Pixel Draw - Number Art Coloring Book                  967.0  2.8M   

                                                      Installs  Type  Price  \
App                                                                           
Photo Editor & Candy Camera & Grid & ScrapBook         10000.0  Free    0.0   
Coloring book moana                                   500000.0  Free    0.0   
U Launcher Lite – FREE Live Cool Themes, Hide Apps   5000000.0  Free    0.0   
Sketch - Draw & Paint                               50000000.0  Free    0.0   
Pixel Draw - Number Art Coloring Book                 100000.0  Free    0.0   

                                                   Content Rating  \
App                                                                 
Photo Editor & Candy Camera & Grid & ScrapBook           Everyone   
Coloring book moana                                      Everyone   
U Launcher Lite – FREE Live Cool Themes, Hide Apps       Everyone   
Sketch - Draw & Paint                                        Teen   
Pixel Draw - Number Art Coloring Book                    Everyone   

                                                                       Genres  \
App                                                                             
Photo Editor & Candy Camera & Grid & ScrapBook                   Art & Design   
Coloring book moana                                 Art & Design;Pretend Play   
U Launcher Lite – FREE Live Cool Themes, Hide Apps               Art & Design   
Sketch - Draw & Paint                                            Art & Design   
Pixel Draw - Number Art Coloring Book                 Art & Design;Creativity   

                                                   Last Updated  \
App                                                               
Photo Editor & Candy Camera & Grid & ScrapBook       07-01-2018   
Coloring book moana                                  15-01-2018   
U Launcher Lite – FREE Live Cool Themes, Hide Apps   01-08-2018   
Sketch - Draw & Paint                                08-06-2018   
Pixel Draw - Number Art Coloring Book                20-06-2018   

                                                           Current Ver  \
App                                                                      
Photo Editor & Candy Camera & Grid & ScrapBook                   1.0.0   
Coloring book moana                                              2.0.0   
U Launcher Lite – FREE Live Cool Themes, Hide Apps               1.2.4   
Sketch - Draw & Paint                               Varies with device   
Pixel Draw - Number Art Coloring Book                              1.1   

                                                     Android Ver  
App                                                               
Photo Editor & Candy Camera & Grid & ScrapBook      4.0.3 and up  
Coloring book moana                                 4.0.3 and up  
U Launcher Lite – FREE Live Cool Themes, Hide Apps  4.0.3 and up  
Sketch - Draw & Paint                                 4.2 and up  
Pixel Draw - Number Art

In [3]:
apps.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10841 entries, Photo Editor & Candy Camera & Grid & ScrapBook to iHoroscope - 2018 Daily Horoscope & Astrology
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Category        10841 non-null  object 
 1   Rating          9367 non-null   float64
 2   Reviews         10840 non-null  float64
 3   Size            10841 non-null  object 
 4   Installs        10840 non-null  float64
 5   Type            10840 non-null  object 
 6   Price           10840 non-null  float64
 7   Content Rating  10840 non-null  object 
 8   Genres          10841 non-null  object 
 9   Last Updated    10840 non-null  object 
 10  Current Ver     10833 non-null  object 
 11  Android Ver     10838 non-null  object 
dtypes: float64(4), object(8)
memory usage: 1.1+ MB


In [4]:
apps.columns

Index(['Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price',
       'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

### check duplicates values if present and drop it

In [5]:
apps_duplicates = apps.duplicated().sum()
print(f'No. of duplicate values present in apps file : {apps_duplicates}')

No. of duplicate values present in apps file : 492


In [6]:
# drop duplicate values
apps_drop_duplicates = apps.drop_duplicates(keep = 'first')

In [7]:
# check after duplicates drop
apps_duplicates = apps_drop_duplicates.duplicated().sum()
print(f'No. of duplicate values present in apps file after dropping : {apps_duplicates}')

No. of duplicate values present in apps file after dropping : 0


In [8]:
apps.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10841 entries, Photo Editor & Candy Camera & Grid & ScrapBook to iHoroscope - 2018 Daily Horoscope & Astrology
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Category        10841 non-null  object 
 1   Rating          9367 non-null   float64
 2   Reviews         10840 non-null  float64
 3   Size            10841 non-null  object 
 4   Installs        10840 non-null  float64
 5   Type            10840 non-null  object 
 6   Price           10840 non-null  float64
 7   Content Rating  10840 non-null  object 
 8   Genres          10841 non-null  object 
 9   Last Updated    10840 non-null  object 
 10  Current Ver     10833 non-null  object 
 11  Android Ver     10838 non-null  object 
dtypes: float64(4), object(8)
memory usage: 1.1+ MB


##### category column

In [9]:
apps['Category'].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
       '1.9'], dtype=object)

In [10]:
apps[apps['Category']== '1.9']

Category  Rating  Reviews    Size  \
App                                                                         
Life Made WI-Fi Touchscreen Photo Frame      1.9    19.0      NaN  1,000+   

                                         Installs Type  Price Content Rating  \
App                                                                            
Life Made WI-Fi Touchscreen Photo Frame       NaN    0    NaN            NaN   

                                                    Genres Last Updated  \
App                                                                       
Life Made WI-Fi Touchscreen Photo Frame  February 11, 2018          NaN   

                                        Current Ver Android Ver  
App                                                              
Life Made WI-Fi Touchscreen Photo Frame  4.0 and up         NaN

In [11]:
apps = apps[apps.Category != '1.9']

In [12]:
apps['Category'].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION'],
      dtype=object)

# rating column

In [13]:
apps['Rating'].unique()

array([4.1, 3.9, 4.7, 4.5, 4.3, 4.4, 3.8, 4.2, 4.6, 3.2, 4. , nan, 4.8,
       4.9, 3.6, 3.7, 3.3, 3.4, 3.5, 3.1, 5. , 2.6, 3. , 1.9, 2.5, 2.8,
       2.7, 1. , 2.9, 2.3, 2.2, 1.7, 2. , 1.8, 2.4, 1.6, 2.1, 1.4, 1.5,
       1.2])

In [14]:
apps['Rating'] = apps['Rating'].replace(np.nan, 0)

In [15]:
apps['Rating'].unique()

array([4.1, 3.9, 4.7, 4.5, 4.3, 4.4, 3.8, 4.2, 4.6, 3.2, 4. , 0. , 4.8,
       4.9, 3.6, 3.7, 3.3, 3.4, 3.5, 3.1, 5. , 2.6, 3. , 1.9, 2.5, 2.8,
       2.7, 1. , 2.9, 2.3, 2.2, 1.7, 2. , 1.8, 2.4, 1.6, 2.1, 1.4, 1.5,
       1.2])

# reviews column

In [16]:
apps['Reviews'].unique()

array([1.59000e+02, 9.67000e+02, 8.75100e+04, ..., 6.03000e+02,
       1.19500e+03, 3.98307e+05])

# size column

In [17]:
apps['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
     

In [18]:
apps['Size'].value_counts()

Varies with device    1695
11M                    198
12M                    196
14M                    194
13M                    191
                      ... 
430k                     1
429k                     1
200k                     1
460k                     1
619k                     1
Name: Size, Length: 461, dtype: int64

In [19]:
apps = apps[apps['Size'] != 'Varies with device']

In [20]:
apps['Size'].value_counts()

11M     198
12M     196
14M     194
13M     191
15M     184
       ... 
430k      1
429k      1
200k      1
460k      1
619k      1
Name: Size, Length: 460, dtype: int64

# installs column

In [21]:
apps['Installs'].unique()

array([1.e+04, 5.e+05, 5.e+06, 5.e+07, 1.e+05, 5.e+04, 1.e+06, 1.e+07,
       5.e+03, 1.e+08, 1.e+03, 5.e+08, 5.e+01, 1.e+02, 5.e+02, 1.e+01,
       1.e+00, 5.e+00, 1.e+09, 0.e+00])

# type column

In [22]:
apps['Type'].unique()

array(['Free', 'Paid'], dtype=object)

# price column

In [23]:
apps['Price'].unique()

array([  0.  ,   4.99,   6.99,   1.49,   2.99,   3.99,   7.99,   5.99,
         1.99,   9.99,   0.99,   9.  ,   5.49,  10.  ,  24.99,  11.99,
        79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,   3.49,  10.99,
         7.49,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,   2.49,
         4.49,   1.7 ,   2.  ,   3.88,  25.99, 399.99,  17.99, 400.  ,
         3.02,   1.76,   4.84,   4.77,   1.61,   1.59,   6.49,   1.29,
         5.  ,  13.99, 299.99, 379.99,  37.99,  18.99, 389.99,  19.9 ,
         8.49,   1.75,  14.  ,   4.85,  46.99, 109.99, 154.99,   3.08,
         2.59,   4.8 ,   8.99,   1.96,  19.4 ,  15.46,   3.04,   4.29,
         2.6 ,   3.28,   4.6 ,  28.99,   2.9 ,   1.97, 200.  ,  89.99,
         2.56,  30.99,   3.61, 394.99,   1.26,   1.2 ,   1.04])

In [24]:
check = len(apps[apps['Price'] < 0.0])
print(f'No. of apps below price 0 : {check}')

No. of apps below price 0 : 0


In [25]:
apps = apps[apps['Price'] >= 0]

In [26]:
apps['Price'].unique()

array([  0.  ,   4.99,   6.99,   1.49,   2.99,   3.99,   7.99,   5.99,
         1.99,   9.99,   0.99,   9.  ,   5.49,  10.  ,  24.99,  11.99,
        79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,   3.49,  10.99,
         7.49,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,   2.49,
         4.49,   1.7 ,   2.  ,   3.88,  25.99, 399.99,  17.99, 400.  ,
         3.02,   1.76,   4.84,   4.77,   1.61,   1.59,   6.49,   1.29,
         5.  ,  13.99, 299.99, 379.99,  37.99,  18.99, 389.99,  19.9 ,
         8.49,   1.75,  14.  ,   4.85,  46.99, 109.99, 154.99,   3.08,
         2.59,   4.8 ,   8.99,   1.96,  19.4 ,  15.46,   3.04,   4.29,
         2.6 ,   3.28,   4.6 ,  28.99,   2.9 ,   1.97, 200.  ,  89.99,
         2.56,  30.99,   3.61, 394.99,   1.26,   1.2 ,   1.04])

# content rating column

In [27]:
apps['Content Rating'].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+',
       'Adults only 18+', 'Unrated'], dtype=object)

# genres column

In [28]:
apps['Genres'].unique()

array(['Art & Design', 'Art & Design;Pretend Play',
       'Art & Design;Creativity', 'Art & Design;Action & Adventure',
       'Auto & Vehicles', 'Beauty', 'Books & Reference', 'Business',
       'Comics', 'Comics;Creativity', 'Communication', 'Dating',
       'Education', 'Education;Creativity', 'Education;Education',
       'Education;Action & Adventure', 'Education;Pretend Play',
       'Education;Brain Games', 'Entertainment',
       'Entertainment;Brain Games', 'Entertainment;Music & Video',
       'Events', 'Finance', 'Food & Drink', 'Health & Fitness',
       'House & Home', 'Libraries & Demo', 'Lifestyle',
       'Lifestyle;Pretend Play', 'Adventure;Action & Adventure', 'Arcade',
       'Casual', 'Card', 'Casual;Pretend Play', 'Strategy', 'Action',
       'Puzzle', 'Sports', 'Word', 'Racing', 'Casual;Creativity',
       'Simulation', 'Adventure', 'Board', 'Trivia', 'Role Playing',
       'Simulation;Education', 'Action;Action & Adventure',
       'Casual;Brain Games', 'Simulat

In [31]:
apps['Genres'].value_counts()

Tools                                739
Entertainment                        537
Education                            496
Medical                              434
Business                             400
                                    ... 
Arcade;Pretend Play                    1
Travel & Local;Action & Adventure      1
Music & Audio;Music & Video            1
Health & Fitness;Education             1
Strategy;Creativity                    1
Name: Genres, Length: 116, dtype: int64

# Last Updated column

In [29]:
apps['Last Updated'].unique()

array(['07-01-2018', '15-01-2018', '01-08-2018', ..., '20-01-2014',
       '16-02-2014', '23-03-2014'], dtype=object)

In [31]:
apps['Last Updated'] = pd.to_datetime(apps['Last Updated'])

C:\Users\Dwijendra\AppData\Local\Temp\ipykernel_21156\3898568761.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  apps['Last Updated'] = pd.to_datetime(apps['Last Updated'])


# current ver column

In [37]:
apps['Current Ver'].unique()

array(['1.0.0', '2.0.0', '1.2.4', ..., '1.0.612928', '0.3.4', '2.0.148.0'],
      dtype=object)

In [38]:
apps['Current Ver'].isnull().sum()

8

In [39]:
apps['Current Ver'] = apps['Current Ver'].replace(np.nan, 0)

In [40]:
apps['Current Ver'].isnull().sum()

0

# Android Ver column

In [41]:
apps['Android Ver'].unique()

array(['4.0.3 and up', '4.2 and up', '4.4 and up', '2.3 and up',
       '3.0 and up', '4.1 and up', '4.0 and up', '2.2 and up',
       '5.0 and up', '6.0 and up', '1.6 and up', '2.1 and up',
       '5.1 and up', '1.5 and up', '7.0 and up', '4.3 and up',
       '4.0.3 - 7.1.1', '2.0 and up', '2.3.3 and up',
       'Varies with device', '3.2 and up', '4.4W and up', '7.1 and up',
       '7.0 - 7.1.1', '8.0 and up', '5.0 - 8.0', '3.1 and up',
       '2.0.1 and up', '4.1 - 7.1.1', nan, '5.0 - 6.0', '1.0 and up',
       '2.2 - 7.1.1', '5.0 - 7.1.1'], dtype=object)

In [42]:
len(apps[apps['Android Ver'] == 'Varies with device'])

56

In [43]:
apps = apps[apps['Android Ver'] != 'Varies with device']

In [44]:
len(apps[apps['Android Ver'] == 'Varies with device'])

0

In [45]:
apps = apps[apps['Android Ver'].notnull()]

In [46]:
apps[apps['Android Ver'].isna()]

Empty DataFrame
Columns: [Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [47]:
apps.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9087 entries, Photo Editor & Candy Camera & Grid & ScrapBook to Parkinson Exercices FR
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   Category        9087 non-null   object        
 1   Rating          9087 non-null   float64       
 2   Reviews         9087 non-null   float64       
 3   Size            9087 non-null   object        
 4   Installs        9087 non-null   float64       
 5   Type            9087 non-null   object        
 6   Price           9087 non-null   float64       
 7   Content Rating  9087 non-null   object        
 8   Genres          9087 non-null   object        
 9   Last Updated    9087 non-null   datetime64[ns]
 10  Current Ver     9087 non-null   object        
 11  Android Ver     9087 non-null   object        
dtypes: datetime64[ns](1), float64(4), object(7)
memory usage: 922.9+ KB


### Now, Reviews dataset 

In [48]:
reviews = pd.read_csv('F:\HiCounselor\datasets\playstore_reviews.csv', index_col = 'App')
reviews.head()

Translated_Review  \
App                                                                        
10 Best Foods for You  I like eat delicious food. That's I'm cooking ...   
10 Best Foods for You    This help eating healthy exercise regular basis   
10 Best Foods for You                                                NaN   
10 Best Foods for You         Works great especially going grocery store   
10 Best Foods for You                                       Best idea us   

                      Sentiment  Sentiment_Polarity  Sentiment_Subjectivity  
App                                                                          
10 Best Foods for You  Positive                1.00                0.533333  
10 Best Foods for You  Positive                0.25                0.288462  
10 Best Foods for You       NaN                 NaN                     NaN  
10 Best Foods for You  Positive                0.40                0.875000  
10 Best Foods for You  Positive                1.00                0.300000

In [49]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64295 entries, 10 Best Foods for You to Houzz Interior Design Ideas
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Translated_Review       37427 non-null  object 
 1   Sentiment               37432 non-null  object 
 2   Sentiment_Polarity      37432 non-null  float64
 3   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), object(2)
memory usage: 2.5+ MB


In [50]:
reviews.columns

Index(['Translated_Review', 'Sentiment', 'Sentiment_Polarity',
       'Sentiment_Subjectivity'],
      dtype='object')

### check duplicates values in reviews dataset if present and drop it

In [51]:
reviews_duplicates = reviews.duplicated().sum()
print(f'No. of duplicate values present in apps file : {reviews_duplicates}')

No. of duplicate values present in apps file : 36299


In [52]:
# drop duplicate values
reviews_drop_duplicates = reviews.drop_duplicates(keep = 'first')

In [53]:
# check after duplicates drop
reviews_duplicates = reviews_drop_duplicates.duplicated().sum()
print(f'No. of duplicate values present in apps file after dropping : {reviews_duplicates}')

No. of duplicate values present in apps file after dropping : 0


In [54]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64295 entries, 10 Best Foods for You to Houzz Interior Design Ideas
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Translated_Review       37427 non-null  object 
 1   Sentiment               37432 non-null  object 
 2   Sentiment_Polarity      37432 non-null  float64
 3   Sentiment_Subjectivity  37432 non-null  float64
dtypes: float64(2), object(2)
memory usage: 2.5+ MB


## translated review column

In [55]:
reviews['Translated_Review'].unique()

array(['I like eat delicious food. That\'s I\'m cooking food myself, case "10 Best Foods" helps lot, also "Best Before (Shelf Life)"',
       'This help eating healthy exercise regular basis', nan, ...,
       'Dumb app, I wanted post property rent give option. Website work. Waste time space phone.',
       'I property business got link SMS happy performance still guys need raise bar guys Cheers',
       'Useless app, I searched flats kondapur, Hyderabad . None number reachable I know flats unavailable would keep posts active'],
      dtype=object)

In [56]:
reviews[reviews['Translated_Review'].isna()]

Translated_Review Sentiment  Sentiment_Polarity  \
App                                                                           
10 Best Foods for You                     NaN       NaN                 NaN   
10 Best Foods for You                     NaN       NaN                 NaN   
10 Best Foods for You                     NaN       NaN                 NaN   
10 Best Foods for You                     NaN       NaN                 NaN   
10 Best Foods for You                     NaN       NaN                 NaN   
...                                       ...       ...                 ...   
Houzz Interior Design Ideas               NaN       NaN                 NaN   
Houzz Interior Design Ideas               NaN       NaN                 NaN   
Houzz Interior Design Ideas               NaN       NaN                 NaN   
Houzz Interior Design Ideas               NaN       NaN                 NaN   
Houzz Interior Design Ideas               NaN       NaN                 NaN   

                             Sentiment_Subjectivity  
App                                                  
10 Best Foods for You                           NaN  
10 Best Foods for You                           NaN  
10 Best Foods for You                           NaN  
10 Best Foods for You                           NaN  
10 Best Foods for You                           NaN  
...                                             ...  
Houzz Interior Design Ideas                     NaN  
Houzz Interior Design Ideas                     NaN  
Houzz Interior Design Ideas                     NaN  
Houzz Interior Design Ideas                     NaN  
Houzz Interior Design Ideas                     NaN  

[26868 rows x 4 columns]

In [57]:
reviews = reviews[reviews['Translated_Review'].notnull()]

In [58]:
reviews[reviews['Translated_Review'].isna()]

Empty DataFrame
Columns: [Translated_Review, Sentiment, Sentiment_Polarity, Sentiment_Subjectivity]
Index: []

# sentiment column

In [59]:
reviews['Sentiment'].unique()

array(['Positive', 'Neutral', 'Negative'], dtype=object)

## Sentiment_Polarity column

In [60]:
reviews['Sentiment_Polarity'].unique()

array([ 1.        ,  0.25      ,  0.4       , ..., -0.52857143,
       -0.37777778,  0.17333333])

In [61]:
reviews[reviews['Sentiment_Polarity'].isna()]

Empty DataFrame
Columns: [Translated_Review, Sentiment, Sentiment_Polarity, Sentiment_Subjectivity]
Index: []

# sentiment subjectivity column

In [62]:
reviews['Sentiment_Subjectivity'].unique()

array([0.53333333, 0.28846154, 0.875     , ..., 0.51145833, 0.7172619 ,
       0.2594697 ])

In [63]:
reviews[reviews['Sentiment_Subjectivity'].isna()]

Empty DataFrame
Columns: [Translated_Review, Sentiment, Sentiment_Polarity, Sentiment_Subjectivity]
Index: []

In [64]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 37427 entries, 10 Best Foods for You to Housing-Real Estate & Property
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Translated_Review       37427 non-null  object 
 1   Sentiment               37427 non-null  object 
 2   Sentiment_Polarity      37427 non-null  float64
 3   Sentiment_Subjectivity  37427 non-null  float64
dtypes: float64(2), object(2)
memory usage: 1.4+ MB


In [65]:
apps.to_csv('playstore_apps_cleaned.csv',encoding = 'utf-8')

In [66]:
reviews.to_csv('playstore_reviews_cleaned.csv',encoding = 'utf-8')